# Generated by Django 3.2 on 2021-04-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoGallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PhotoGallery.category'),
        ),
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(related_name='liked_photo', to='PhotoGallery.User'),
        ),
    ]
