# Generated by Django 3.2 on 2021-04-14 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PhotoGallery', '0002_auto_20210413_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(related_name='liked_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
